language: ruby

rvm:
- 2.3.0

before_script:
- chmod +x ./script/cibuild

script: "./script/cibuild"

branches:
  only:
  - master
  
deploy:
  provider: s3
  access_key_id: AKIAII45SI4IQATGXTGQ
  secret_access_key:
    secure: pB9zSJL3Z9HKujDxIQJLQVmKr73+6SNmHTx5p9j57JNqYWzrhUxHZb9AIW4c23F11ye+t+dTu4Ru2ov4xTDW4SC6BzMHCbXDOUNYAQRzgRigeE0+LavY035R14SJWMko0HTUJKN9XyxjZwMPjCMDkZlR0vNW7hETNtBU8CNSXg062iiLdRGeko4A0BXFQlbkojXY8BRRTLfAz8q4dgZ5TeNLrhUZQ2jVA0XvFrzArBDO7lglHgk7jcx2NNaLfIH/KmhcIVmNJEALsJRIbBWcWDKI+EhhAeffOw/yGwpV+jhq9akH40e0POtXSPwsvyJpsXNVywi9Z3iakYJmzsEb98hQFEnu48p9jkxu0iImF+5KamnC+krB4sNfMK+yT6OPxDV+xKB046XmP5RjoY1Yt+Wi0ZSN9vZJa6jfBni9LQkcqcqPIm1skpmpvytU07pOI7/hRfZ0mK9R8PkgXLn0DksO8+guqonj9p+s9ur02kVRtlWdwzNLWebAS2jDJO2jYldzN0mCASyRtZUlOlYdgtvbr/zMX302NyD8On9lK6TdRO7UYFDKYCMDEfdl+dnArUiNpPLxg0hoclQgy4rzz8ns9GRHbs+4nSPLXgeabJTNMsOBKMKaTXGACAmU6Z1lJEVeXBRhwWU4M6QNuThUavQ5OH5zHIbIUZFXsQ/yQFI=
  bucket: www.devoctomy.com
  local-dir: _site
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  on:
    repo: devoctomy/devoctomy.com
