# Site settings
email: nick@devoctomy.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: devoctomy
description: The home of devoctomy, software development
url: "http://www.devoctomy.com"
twitter_username: devoctomy
default_img: /assets/images/surfacebook_small.jpg

# Profile settings
name: Nick Pateman
profile_img: /assets/images/nick.jpg
profile: CEO and developer for devoctomy.  Gadget and dance music enthusiast, skinny but weighs just enough to not blow away in a strong breeze.
social:
  github: https://github.com/settings/profile
  facebook: https://www.facebook.com/devoctomy/

# Build settings
include: ["_categories"]
exclude: ["Gemfile", "Gemfile.lock", "vendor"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, jekyll, octopress-autoprefixer, travis]
